# 1. Объявляем два последовательных этапа конвейера
stages:
  - build-and-pack
  - deploy-to-k8s

# Этап сборки
build-java-app:
  stage: build-and-pack
  tags:
    - build

  script:
    # 1. Runner авторизируется в Container Registry
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN

    # 2. Runner запускает сборку Docker-образа, используя Dockerfile. Флаг --no-cache принудительно запускает компиляцию заново
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:latest .

    # 3. Runner отправляет готовый образ на GitLab Container Registry
    - docker push $CI_REGISTRY_IMAGE:latest

deploy-java-app:
  stage: deploy-to-k8s
  tags:
    - build # Используется тот же Runner
  script:
    # 1. Создаем пустую папку для SSH-настроек в домашней директории раннера
    - mkdir -p ~/.ssh

     # 2. Записываем текст ключа во временный файл
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

    # 3. Выставляем жесткие права безопасности "только для владельца"
    - chmod 600 ~/.ssh/id_rsa

    # 4.1. Запускаем SSH-деплой, используя файл ключа
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o WarnWeakCrypto=no root@5.35.28.230 "kubectl rollout restart deployment/spring-backend-deployment"

    # Ждем, пока новые контейнеры полностью подменят старые
    - sleep 15

    # 4.2. Перезапускаем службу проброса портов, чтобы она переподключилась к новым подам
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o WarnWeakCrypto=no root@5.35.28.230 "sudo systemctl restart k8s-port-forward.service"
    
    # 5. Удаляем приватный ключ с диска после выполнения команды
    - rm -f ~/.ssh/id_rsa