# Объявляем этапы конвейера
stages:
  - build-and-pack
  - deploy-to-k8s

# Этап сборки
build-java-app:
  stage: build-and-pack
  tags:
    - build

  script:
    # 1. Runner авторизируется в Container Registry
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN

    # 2. Runner запускает сборку Docker-образа, используя Dockerfile. Флаг --no-cache принудительно запускает компиляцию заново
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:latest .

    # 3. Runner отправляет готовый образ на GitLab Container Registry
    - docker push $CI_REGISTRY_IMAGE:latest

deploy-java-app:
  stage: deploy-to-k8s
  tags:
    - build # Используется тот же Runner
  script:
    # 1. Подготовка SSH-инфраструктуры
    - mkdir -p ~/.ssh                         # Создаем папку для SSH в домашней директории раннера
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa # Записываем текст ключа во временный файл
    - chmod 600 ~/.ssh/id_rsa                 # Выставляем жесткие права безопасности

    # 2. Копируем папку k8s/ с локальной машины на Master-ноду по SCP
    - scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r k8s/ root@5.35.28.230:/root/my-k8s-manifests/

    # 3. Kubernetes применяет скопированные файлы
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o WarnWeakCrypto=no root@5.35.28.230 "kubectl apply -f /root/my-k8s-manifests/"

    # 4. Форсируем скачивание свежего Docker-образа, если сам манифест не менялся
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o WarnWeakCrypto=no root@5.35.28.230 "kubectl rollout restart deployment/spring-backend-deployment"

    # 5. Подчищаем за собой секретные ключи
    - rm -f ~/.ssh/id_rsa