services:
  # Название службы
  java-app:
    # Инструкция: "Если образа нет в памяти, загляни в текущую папку (.), найди Dockerfile и собери его"
    build: .

    # Понятное имя для контейнера, которое мы видим в docker ps
    container_name: spring-boot-backend

    # Проброс портов: связываем порт 8080 нашей Ubuntu с внутренним портом 8080, который слушает Spring Boot внутри контейнера
    ports:
      - "8080:8080"

    # Docker сам поднимет этот контейнер обратно в память
    restart: always