# Сетевой адрес облачной базы данных в Москве
spring.datasource.url=jdbc:postgresql://111.88.218.191:5432/java_app_db

# Логин и пароль, которые мы создали через Ansible
spring.datasource.username=java_user
spring.datasource.password=SuperSecureJavaPassword123

# Настройка Hibernate: он автоматически создаст таблицы в базе данных при старте
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true